#!/usr/bin/env python3

import sys

sys.path.append('../lib')

import srp

args = sys.argv[1:]
if len(args) != 2:
    print('setpass user password')
    sys.exit(1)

passwords = []

lines = []
try:
    lines = open('passwd').readlines()
except IOError:
    pass

lines = [x.strip() for x in lines]

(user, passwd) = args
newline = user + ':' + srp.genpass(bytes(passwd, 'ascii'))

found = False
for i in range(len(lines)):
    u = lines[i].split(':')[0]
    if user == u:
        lines[i] = newline
        found = True
        break

if not found:
    lines.append(newline)

f = open('passwd', 'w')
f.write('\n'.join(lines) + '\n')






