#!/usr/bin/env python3

import sys
sys.path.append('../lib')

import socketserver
from srp import AuthServer

class AuthHandler(socketserver.BaseRequestHandler):
    def handle(self):
        s = AuthServer('passwd')
        s.run(self.request)

with socketserver.TCPServer(('localhost', 8888), AuthHandler) as server:
    server.serve_forever()
