#!/usr/bin/env python3

import sys
sys.path.append('../lib')
import english

enc = [bytes.fromhex(x) for x in open('4.txt').readlines()]

decs = []
for e in enc:
    for by in range(256):
        dec = bytes([x^by for x in e])
        decs.append((english.score(dec), dec))

decs = sorted(decs)
print(decs[-1][1])
