#!/usr/bin/env python3

import sys
sys.path.append('../lib')

from crmath import mt19937, mt19937_untemper
import time

r = mt19937()

mt = []
for i in range(r.n):
    mt.append(mt19937_untemper(r.next()))

s = mt19937()
s.mt = mt

for i in range(1000):
    y1 = r.next()
    y2 = s.next()
    print(y1, y2)

