#!/usr/bin/env python3

import sys
sys.path.append('../lib')
import english

enc = bytes.fromhex(open('input.txt').read())
    
decs = []
for by in range(256):
    dec = bytes([x^by for x in enc])
    decs.append((english.score(dec), dec))

decs = sorted(decs)
print(decs[-1][1])
