#!/usr/bin/env python3

import sys
sys.path.append('../lib')

from diffhell import DHKeys, DHSession

alice = DHKeys()
bob = DHKeys()

alice_session = DHSession(alice, bob.public())
bob_session = DHSession(bob, alice.public())

print('alice symmetric key', alice_session.key().hex())
print('bob symmetric key  ', bob_session.key().hex())
