#!/usr/bin/env python3

import sys
sys.path.append('../lib')
from xor import xorb

lines = [x.strip() for x in open('input.txt').readlines()]
lines = [bytes.fromhex(x) for x in lines if x != '']

out = xorb(lines[0], lines[1])
print(out)
print(out.hex())
